---
- hosts: centos7
  become: yes
  vars:
    mysql_root_password: password

  tasks:
  # - name: Install firewalld
  #   yum: name=firewalld state=present
  # - name: Start firewalld and enabled
  #   service: name=firewalld state=started enabled=true   
  
  - name: install mariadb-server
    yum: name=mariadb-server update_cache=yes state=present
  - name: start up mysql service and ensure sql is enabled
    service: name=mariadb state=started enabled=true
  
  # - name: Configure firewalld rules
  #   firewalld: service=http permanent=yes immediate=yes state=enabled
  - name: Install Python
    yum: name=python3 state=present
    yum: name=MySQL-python state=present
  - name: update mysql root password for all root accounts
    mysql_user:
      check_implicit_admin: true
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: root
      password: "{{ mysql_root_password }}"
      host: localhost
      # priv: "*.*:ALL,GRANT"
  
  - name: Add user ecomuser to mariadb
    mysql_user:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      user: ecomuser
      password: "ecompassword"
      priv: "*.*:ALL"
      state: present
  
  - name: Create Sql database
    mysql_db: name=ecomdb login_user=root login_password="{{ mysql_root_password }}" state=present config_file=/etc/my.cnf
  
  # @@@@@ RUN ONCE SO COMMENTED @@@@@ 
  # - name: Import database
  #   mysql_db: name=ecomdb login_user=root login_password="{{ mysql_root_password }}" state=import target=/home/ansible/db-load-script.sql single_transaction=true
      
  - name: Create webserver
    yum: name=httpd state=present 
  - name: Start webserver and ensure enabled
    service: name=httpd state=started enabled=true
    
  - name: Install Git
    yum: name=git state=present
  
  # @@@@ RUN ONLY ONCE @@@
  # - name: Download code from Github repo
  #   git: repo=https://github.com/kodekloudhub/learning-app-ecommerce.git dest=/var/www/html
  
  # @@@ ONLY SUPPORTED IN ANSIBLE-CORE 2.11 @@@@@
  # - name: Update index.php replace 54.173.124.43 with localhost
  #   lineinfile:
  #     path: /var/www/html/index.php
  #     search_string: '54.173.124.43'
  #     line:  localhost
  #     owner: root
  #     group: root
  #     mode: 0644
   # @@@ ONLY SUPPORTED IN ANSIBLE-CORE 2.11 @@@@@
  # - name: Update httpd.conf replace index.html with index.php
  #   lineinfile:
  #     path: /etc/httpd/conf/httpd.conf
  #     search_string: 'index.html'
  #     line: index.php
  #     owner: root
  #     group: root
  #     mode: 0644
  # - name: create database
  #   mysql_db: "name=ecomdb state=present login_user=root login_password={{ mysql_root_password }}"

