# First create Dockerfile on docker host with be contents
# FROM tomcat:latest
# RUN cp -R /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps
# COPY ./*.war /usr/local/tomcat/webapps
#
---
- name: create container
  #hosts: docker
  hosts: localhost
  tasks:
    #- shell: |
    #  docker build -t regapp:v2 .
    #  docker run -d --name register-server -p 8080:8080 regapp:v2
  - name: stop existing container
    command: docker stop reg-server
    ignore_errors: yes
  - name: remove existing container
    command: docker rm reg-server
    ignore_errors: yes
  - name: remove image
    command: docker rmi krreesh/myregiapp:v1
    ignore_errors: yes
  - name: Create a container
    command: docker run -d --name reg-server -p "8080:8080" krreesh/myregiapp:v1
