---
- name: create physical volume
  hosts: ip-172-31-91-42.ec2.internal
  become: true
  tasks:
  - name: Create a new ext4 primary partition
    community.general.parted:
      device: /dev/xvdb
      number: 2
      state: present
      flags: [ lvm ]
      fs_type: ext4
      part_start: '75%'

  - name: Create swap partition
    community.general.parted:
      device: /dev/xvdb
      number: 1
      state: present
      flags: [ swap ]
      fs_type: ext3
    #   part_end: '25%'  
      
  - name: read device information (always use unit when probing)
    parted: 
      device: /dev/xvdb
      unit: MiB
    register: xvdb_info
      
  - name: remove
    parted:
      device: /dev/xvdb
      state: absent
      number: '{{ item.num }}'
    #   number: 2
    loop: '{{ xvdb_info.partitions }}'
