---
- name: Install AWS Cliv2
  hosts: all
  gather_facts: no
  tasks:
  - name: update cli
    win_shell: msiexec.exe /i https://awscli.amazonaws.com/AWSCLIV2.msi /qn
  
  - name: check version
    win_shell: aws --version
    register: version
  - name: print version
    debug:
      var: version
