---
- name: Test WinRM connection
  hosts: ec2-54-173-130-171.compute-1.amazonaws.com
  gather_facts: no
  tasks:
    - name: Test connection
      win_ping:
      vars:
        ansible_winrm_server_cert_validation: ignore
