---
- name: Install Windows updates
  hosts: all
  gather_facts: no
  tasks:
  - name: Install all security, critical, and rollup updates without a scheduled task
    ansible.windows.win_updates:
      category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      log_path: C:\ansible_install.txt
      reboot: yes
      reboot_timeout: 1200
    register: update_result
  - name: reboot host if required
      win_reboot:
      when: update_result.reboot_required

